FROM php:5-apache

WORKDIR /home/web
ADD src /home/web

RUN docker-php-ext-install mysqli pdo pdo_mysql

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    vim \
    git

# Update apache site for our custom location 
COPY ./serverConfiguration/000-default.conf /etc/apache2/sites-available/

EXPOSE 80

ADD ./scripts/entrypoint.dev.sh /usr/bin/
RUN chmod -v +x /usr/bin/entrypoint.dev.sh

# Start the service
ENTRYPOINT ["bash", "/usr/bin/entrypoint.dev.sh"]
