# Based on info found at
# https://github.com/CodingItWrong/rails-docker-mac
# https://github.com/alienfast/docker-rails/issues/4
version: '2'
services:
  db:
   image: mysql:5.7.16
   container_name: mysql
   volumes:
     - ./mysql:/var/lib/mysql
   env_file:
     - '.env.db'
   ports:
     - "3306:3306"
  web:
   build: .
   container_name: web
   links:
     - db
   volumes:
     - ./src:/var/www/html
   env_file:
     - '.env.web'
   ports:
      # format is host-port:docker-port
      # this will forward port 3000 on the docker to port 3000 on your host
      # to forward to 3000 to port 80 use
      # - "80:3000"
     - "8080:80"
   depends_on:
     - db
