version: '3'
services:
  db:
   image: mysql:5.7
   container_name: mysql
   volumes:
     - ./mysql:/var/lib/mysql
   env_file:
     - './env/.env.dev.db'
   ports:
     - "3306:3306"
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: web
    links:
      - db
    volumes:
      - ./src:/home/web   
    env_file:
      - './env/.env.dev.web'
    ports:
      - "8080:80"
    depends_on:
      - db
